# frozen_string_literal: true

source "https://rubygems.org"

gemspec

gem "rake", "~> 13.0"
gem "rake-compiler", "~> 1.2"
# Keep in sync with the `rb-sys` version used by the Rust crate.
gem "rb_sys", "~> 0.9.128"
gem "rspec", "~> 3.13"

group :test do
  gem "actionpack", ">= 7.0"
  gem "rack-test", "~> 2.1"
  gem "railties", ">= 7.0"
  # For checking the dummy app by hand via `bundle exec rackup spec/dummy/config.ru`
  gem "webrick", "~> 1.9"
end
